### PR TITLE
Feature/scale

### PR DESCRIPTION
**Pull request by misteral**
Added tricky size(scale qr code canvas) as option.

### CODE REVIEW

**Comment by kciter** [comment]
Thank you. 😄 
Would you like to work together as a collaborator?

**Comment by misteral** [comment]
@kciter 
Hi, Yes, NP.

**Comment by kciter** [comment]
I added you as a collaborator. Thank you. :)

**Comment by misteral** [comment]
Thank you, too. I will mention you in my PR's for approve features.

**Pull request merged**
